# Generated by Django 3.0.8 on 2020-07-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_textfield',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_thumbnail_url',
        ),
    ]
